feat: add send_voice_messages permission
DisnakeDev/disnake pull request #1006
Opened 2023-04-16 05:10 UTC by onerandomusername

## Summary

Adds the new permission for sending voice messages.

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `pdm lint`
    - [x] I have type-checked the code by running `pdm pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-04-16 14:16 UTC, shiftinv commented
This should be combined with the other voice message related changes, and have one changelog entry for the permission bit + other fields.
I've pushed the other things [here](https://github.com/DisnakeDev/disnake/compare/feature/voice-messages), would be great if you could pull them into this PR.

2023-04-16 22:04 UTC, onerandomusername commented
> This should be combined with the other voice message related changes, and have one changelog entry for the permission bit + other fields. I've pushed the other things [here](https://github.com/DisnakeDev/disnake/compare/feature/voice-messages), would be great if you could pull them into this PR.

I'd rather get the permission in now, as that doesn't require much of a review.

2023-04-16 22:43 UTC, shiftinv commented
> I'd rather get the permission in now, as that doesn't require much of a review.

Fine, I suppose.

2023-04-16 22:44 UTC, shiftinv requested changes
Not having `send_messages` permissions should implicitly deny `send_voice_messages`:
![image](https://user-images.githubusercontent.com/8530778/232347058-60571181-f26f-4b15-ad59-f163e35efd4e.png)

2023-04-16 22:45 UTC, onerandomusername commented
> Not having `send_messages` permissions should implicitly deny `send_voice_messages`: ![image](https://user-images.githubusercontent.com/8530778/232347058-60571181-f26f-4b15-ad59-f163e35efd4e.png)

Fair, I forgot about this because that is part of the code is completely wrong.

2023-04-16 22:53 UTC, shiftinv commented on changelog/1006.feature.rst
The old changelog entry should be updated to match as well

2023-04-16 22:53 UTC, shiftinv commented on disnake/permissions.py
> +            send_voice_messages=True,
This is missing a `versionchanged`, same with `.all_channel()`

2023-05-02 22:07 UTC, shiftinv commented on disnake/permissions.py
> +            Added :att:`send_voice_messages` permission.
```suggestion
            Added :attr:`use_soundboard` and :attr:`send_voice_messages` permissions.
```

2023-05-02 22:07 UTC, shiftinv commented on disnake/permissions.py
> +            Added :att:`send_voice_messages` permission.
```suggestion
            Added :attr:`send_voice_messages` permission.
```

2023-05-23 11:40 UTC, shiftinv approved these changes
lgtm, ty

2023-05-23 11:40 UTC, merged