fix(enum): remove Party Type enum (#1023)
DisnakeDev/disnake pull request #1035
Opened 2023-05-10 01:31 UTC by KnownBlackHat

## Summary

Deprecates  the `PartyType` enum #1023   

## Checklist

- [X] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [X] I have formatted the code properly by running `pdm lint`
    - [X] I have type-checked the code by running `pdm pyright`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-05-10 01:41 UTC, Victorsitou requested changes
The enum should be deprecated rather than removed to avoid breaking changes

2023-05-10 01:48 UTC, KnownBlackHat commented
> 

yep doing that rn

2023-05-15 10:40 UTC, shiftinv reviewed
Could you also add a deprecation note (`.. deprecated:: 2.9` etc.) below here, similar to other deprecation notes? https://github.com/DisnakeDev/disnake/blob/473bafbbdda4185696d29033b4f3ba05e0126757/docs/api/voice.rst?plain=1#L111-L113

2023-05-15 10:40 UTC, shiftinv commented on disnake/abc.py
> +            )
`target_application` is unlikely to be removed, it's still a valid and documented API field.
It should however now support `Object`s as an alternative (with accompanying changelog and `versionchanged` documentation), and `PartyType` for backwards compatibility until the next version

2023-05-15 10:40 UTC, shiftinv commented on changelog/1035.deprecate.rst
> +If anything, providing activities should really be more of a bot's responsibility, not the library's, so we should consider deprecating and removing this enum.
```suggestion
The :class:`PartyType` enum is deprecated, as voice activity IDs are not officially documented and the enum regularly becomes outdated.
```
It doesn't have to be too wordy, and multiline changelogs don't render that well:
![image](https://github.com/DisnakeDev/disnake/assets/8530778/42e222fc-885c-4df1-93a6-9054a702ae42)

2023-05-22 15:22 UTC, shiftinv commented on disnake/abc.py
> +            )
This doesn't seem to be resolved yet (and neither is the comment above)?

At least for this comment, something like [this](https://gist.github.com/shiftinv/e8f091e813e5a598af10e0c01e538a08) could work, I believe.

2023-06-12 19:26 UTC, Victorsitou approved these changes

2023-06-13 14:53 UTC, shiftinv approved these changes

2023-06-13 14:59 UTC, merged