refactor(tooling): Switch to ruff-format for formatting.
DisnakeDev/disnake pull request #1169
Opened 2024-03-19 15:58 UTC by elenakrittik

## Summary

Replaces black with ruff-format. The changes made would've been made by black as well if we were to update black to latest version.

## Checklist

- [ ] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `pdm lint`
    - [ ] I have type-checked the code by running `pdm pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2024-05-14 13:15 UTC, elenakrittik commented
Ready for consideration!

2024-05-19 13:11 UTC, shiftinv requested changes
I think I voiced my concerns about all-in-one tooling on discord before; to summarize, not being able to update linter and formatter separately anymore isn't ideal.
If one wants to update ruff to fix a linter bug, but doesn't want the formatting changes a newer version would potentially bring, you're pretty much out of luck.

Still, I'm willing to give this a try, especially given the pretty substantial performance difference. :>
There's potential for lots of fun merge conflicts in other PRs here, so I'd prefer only merging this after the next release - hope that's understandable

2024-05-19 13:13 UTC, Enegg commented on disnake/ext/commands/params.py
>          # fmt: off
It does but not within expressions
It should be
```py
# fmt: off
foo = {
    ...
}
# fmt: on
```
or
```py
foo = {
    ...
}  # fmt: skip
```

2024-05-19 14:06 UTC, elenakrittik commented on disnake/ext/commands/params.py
>          # fmt: off
165ab848

2024-05-19 14:06 UTC, elenakrittik commented on disnake/types/activity.py
> +    )
165ab848

2024-05-19 14:09 UTC, elenakrittik commented
> I think I voiced my concerns about all-in-one tooling on discord before; to summarize, not being able to update linter and formatter separately anymore isn't ideal.

Don't see much of an issue with that, but given that

> I'd prefer only merging this after the next release

We'll have a chance to test it 😄

2024-05-19 16:52 UTC, Enegg requested changes
https://github.com/DisnakeDev/disnake/pull/1169/commits/165ab8484b816187a54fda57b1492503299d38ab Undo the formatting changes too

2024-05-19 17:48 UTC, elenakrittik commented
> https://github.com/DisnakeDev/disnake/pull/1169/commits/165ab8484b816187a54fda57b1492503299d38ab Undo the formatting changes too

Excuse me, why?

2024-05-19 17:54 UTC, Enegg commented
> Excuse me, why?

What's the point of `fmt: off` if the thing it was guarding from being formatted, has been formatted?
https://github.com/DisnakeDev/disnake/pull/1169/files#diff-6377fad5f75948c1eaa880c932839dd3f47b01c21056433ada31632cb518a665R480-R499

2024-06-28 10:52 UTC, elenakrittik commented
[Ruff v0.5 has just been released](https://github.com/astral-sh/ruff/releases/tag/0.5.0), so technically this can move forward. I'll try and find some time to update this

2025-01-27 17:56 UTC, shiftinv commented
Would it be possible for you to update this, now that the next version has been released? The library already uses ruff v0.8.0 now, and it appears that there haven't been any format changes between v0.3.4 and v0.8.0, plus only a couple minor string format changes from v0.8.0 to v0.9.3/latest. :eyes:

2025-01-27 19:07 UTC, elenakrittik commented
Should be good now!

2025-01-27 19:32 UTC, shiftinv commented on disnake/ext/commands/params.py
>      }
The `# fmt: off` (and counterpart) need to be outside the expression: https://github.com/DisnakeDev/disnake/pull/1169#discussion_r1606030290
Would be nice to keep the alignment here as before, it makes the mapping more readable, at least a little bit
```suggestion
    # fmt: off
    TYPES: ClassVar[Dict[type, int]] = {
        str:                                               OptionType.string.value,
        int:                                               OptionType.integer.value,
        bool:                                              OptionType.boolean.value,
        disnake.abc.User:                                  OptionType.user.value,
        disnake.User:                                      OptionType.user.value,
        disnake.Member:                                    OptionType.user.value,
        Union[disnake.User, disnake.Member]:               OptionType.user.value,
        # channels handled separately
        disnake.abc.GuildChannel:                          OptionType.channel.value,
        disnake.Role:                                      OptionType.role.value,
        disnake.abc.Snowflake:                             OptionType.mentionable.value,
        Union[disnake.Member, disnake.Role]:               OptionType.mentionable.value,
        Union[disnake.User, disnake.Role]:                 OptionType.mentionable.value,
        Union[disnake.User, disnake.Member, disnake.Role]: OptionType.mentionable.value,
        float:                                             OptionType.number.value,
        disnake.Attachment:                                OptionType.attachment.value,
    }
    # fmt: on
```

2025-01-27 19:33 UTC, shiftinv commented on disnake/types/activity.py
> +    )
also resurrecting this thread for the rebase c:

2025-01-27 19:46 UTC, Enegg commented on disnake/ext/commands/params.py
>      }
I suggest using `}  # fmt: skip` on the closing bracket, that way it's effectively bound to the statement

2025-01-28 16:47 UTC, shiftinv approved these changes
lgtm, thank you!

2025-01-28 16:47 UTC, merged