fix: bugs with link buttons
DisnakeDev/disnake pull request #252
Opened 2022-01-05 21:27 UTC by Victorsitou

## Summary

<sup>First bug</sup>
This PR fixes a bug for when a view is refreshed, and it has a link button, since they aren't dispatchable, they won't be in this dict,
![image](https://user-images.githubusercontent.com/67214928/148285588-a554cde2-f0a3-4c1b-a356-164fcf0363cb.png)
so it tries to get the link button from it,
https://github.com/DisnakeDev/disnake/blob/2e5488572cc25432101da3328f44ae638d05dae6/disnake/ui/view.py#L409-L413
and since it isn't there, it'll raise a `KeyError` error, and then it tries to create a new item (`_component_to_item`)
https://github.com/DisnakeDev/disnake/blob/2e5488572cc25432101da3328f44ae638d05dae6/disnake/ui/view.py#L77-L81
which calls `Button.from_component` which defines `row` to `None`
https://github.com/DisnakeDev/disnake/blob/2e5488572cc25432101da3328f44ae638d05dae6/disnake/ui/button.py#L203-L213

There is also another related bug, but I really don't understand why it happens :/

Closes #251 error

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `pre-commit run --all-files`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-01-06 22:52 UTC, onerandomusername requested changes

2022-01-06 22:52 UTC, onerandomusername commented on disnake/ui/view.py
> +                        break
should this be a continue? I think this would break with 2 link buttons.

2022-01-06 22:58 UTC, onerandomusername commented on disnake/ui/view.py
> +                        break
Nope, stand corrected, setting this to continue makes the bug reappear.

2022-01-06 22:59 UTC, onerandomusername approved these changes
LGTM. Tested where the bug initially was found, this solves the problem with link button jumping.

2022-01-07 11:10 UTC, EQUENOS commented on disnake/ui/view.py
> +                        child.type.value == 2  # Button
It'd be better to change this to `child.type is ComponentType.button`

2022-01-13 21:15 UTC, shiftinv approved these changes

2022-01-19 15:19 UTC, merged