feat: jump to channel properties
DisnakeDev/disnake pull request #319
Opened 2022-01-31 02:27 UTC by onerandomusername

## Summary
feat: jump to channel properties

these were not added to GroupChannel since
1) the integration has been discontinued and
2) those GroupChannels don't show up in the official user interface so jump urls aren't useful

added jump_url to all guild channels because of the tentative text in voice feature
and I don't see it being a problem to implement it this way
it was also the easiest way to implement it.

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint` or `pre-commit run --all-files`
- [x] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-02-09 11:19 UTC, m1raynee approved these changes

2022-02-10 17:42 UTC, shiftinv requested changes
Looks good, `jump_url` is missing from `PartialMessageable` though.

2022-02-10 20:45 UTC, onerandomusername commented
That's fully intentional. PartialMessageables do not have a guild object, and jump urls have a guild id in them.

2022-02-11 15:28 UTC, EQUENOS approved these changes

2022-02-11 15:30 UTC, shiftinv commented
> That's fully intentional. PartialMessageables do not have a guild object, and jump urls have a guild id in them.

They don't have to, it appears to work fine with `@me` even for guild channels, which could be a valid tradeoff for `PartialMessageable`

2022-02-13 11:33 UTC, onerandomusername commented
Interesting, it did not work like that when i initially tested it.

2022-02-13 13:51 UTC, EQUENOS commented
> > That's fully intentional. PartialMessageables do not have a guild object, and jump urls have a guild id in them.
> 
> They don't have to, it appears to work fine with `@me` even for guild channels, which could be a valid tradeoff for `PartialMessageable`

This is hacky. I'm not sure if we should do that.

2022-02-13 18:47 UTC, shiftinv approved these changes

2022-02-13 18:49 UTC, onerandomusername commented
> > This is hacky. I'm not sure if we should do that.
> 
> Actually why not, it's `PartialMessageable` anyways. Fair tradeoff.

Its *too* hacky, IMO.

2022-02-13 21:49 UTC, merged