fix(Guild): missing return in `get_command`
DisnakeDev/disnake pull request #333
Opened 2022-02-07 15:32 UTC by shiftinv

## Summary

as title, fixes a missing `return` and updates the docstring (partially taken from #275)

## Checklist

- [ ] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint` or `pre-commit run --all-files`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-02-07 19:12 UTC, Victorsitou requested changes
The docstring is wrong (alternatively a Return would be nice)
![image](https://user-images.githubusercontent.com/67214928/152855614-cc310abf-60a3-4e2d-9ef7-733605e17cef.png)

2022-02-07 19:23 UTC, shiftinv commented
The docstring is already mostly fixed by #275, could fix it there with all the other documentation updates:
![image](https://user-images.githubusercontent.com/8530778/152857313-40154b24-2e77-4e18-a4a6-69b7164c759c.png)

2022-02-07 19:25 UTC, Victorsitou approved these changes

2022-02-07 19:27 UTC, onerandomusername approved these changes
looks good. On the fence about the docstring, tho.

2022-02-08 12:05 UTC, EQUENOS approved these changes

2022-02-08 12:05 UTC, merged