fix(slashcmd): improve handling of uppercase slash command names
DisnakeDev/disnake pull request #346
Opened 2022-02-12 15:31 UTC by shiftinv

## Summary

This PR fixes command caching and `InvokableSlashCommand.qualified_name` for names with uppercase chars, as the inner object (`body`/`option`) converts the name to lowercase, but command caching uses the (unmodified) `InvokableApplicationCommand.name` instead of `.body.name`.
Also adds `SubCommandGroup.body` which was missing before, to match the other types.

fixes #336

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint` or `pre-commit run --all-files`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-02-12 15:37 UTC, m1raynee requested changes
looks good

2022-02-12 15:37 UTC, m1raynee commented on disnake/ext/commands/slash_core.py
> +        self.qualified_name = self.name
```suggestion
        self.qualified_name = self.name = self.body.name
```

2022-02-12 15:41 UTC, shiftinv commented on disnake/ext/commands/slash_core.py
> +        self.qualified_name = self.name
fixed, thanks

2022-02-12 15:42 UTC, m1raynee approved these changes

2022-02-13 14:07 UTC, EQUENOS approved these changes

2022-02-13 14:09 UTC, merged