deprecate and update voice regions
DisnakeDev/disnake pull request #357
Opened 2022-02-16 07:47 UTC by onerandomusername

## Summary

- update list of valid voice regions
- deprecate guild.region

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint` or `pre-commit run --all-files`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-02-16 18:04 UTC, shiftinv requested changes
The guild voice region is present in a few more places, ideally those should be deprecated as well:
- `Client.create_guild`
- `Template.create_guild`
- audit log change key (docs)

Could you also update the docs of `VoiceRegion` to match the new region list?

2022-02-21 01:17 UTC, onerandomusername commented on disnake/guild.py
> +        will be a :class:`str` if the value is not recognised by the enumerator.
Its still possible to be a string if it not recognized, afaik

2022-02-21 01:41 UTC, shiftinv commented on disnake/guild.py
> +        will be a :class:`str` if the value is not recognised by the enumerator.
`try_enum` dynamically creates an enum value if it doesn't exist, so this should never be a `str`

2022-02-21 09:15 UTC, onerandomusername commented on disnake/guild.py
> +        will be a :class:`str` if the value is not recognised by the enumerator.
https://github.com/DisnakeDev/disnake/pull/357/commits/1c910a52a49f51f6632aad4e2dfa6fb024e4e777

2022-02-21 22:00 UTC, onerandomusername commented on disnake/guild.py
>              fields["region"] = str(region)
I think its fine to leave in HTTPClient as while its deprecated, the api still will accept it? Not sure.

2022-02-21 22:11 UTC, onerandomusername commented on disnake/guild.py
>              fields["region"] = str(region)
Removed https://github.com/DisnakeDev/disnake/pull/357/commits/555c63be4e474e3a03865c14105320f304d01a4e

2022-02-21 22:31 UTC, shiftinv approved these changes

2022-02-21 22:32 UTC, merged