Docs: cache bust and faster hoverxref
DisnakeDev/disnake pull request #393
Opened 2022-03-06 03:29 UTC by bast0006

## Summary

This PR busts the CSS/JS caches because despite RTD's documentation stating they "bust the cache" every time a new version is submitted, there have been reports of users with the unfortunate experience of having old JS running with newer html.

This PR also replaces the live version of sphinx-hoverxref with a forked version that has been altered to utilize lazy-loaded hoverxref hooks instead of on-page-load, which should dramatically speed up page load times.

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-03-06 03:35 UTC, onerandomusername requested changes
The change looks good but we have to wait for a pypi release of sphinx-hoverxref.

2022-03-06 03:35 UTC, onerandomusername commented on setup.py
> +        "sphinx-hoverxref @ git+https://github.com/bast0006/sphinx-hoverxref@8c36803a3da891182543f599ac3799cbc1ef8a3c",
The problem is we won't be able to merge this pr until this is on pypi. Pypi requires all dependencies of projects on pypi also be on pypi.

2022-06-06 00:02 UTC, onerandomusername commented
@bast0006 any status on when the pr to sphinx-hoverxref will be made?

2022-09-17 03:27 UTC, onerandomusername commented
update: the pr has been made: https://github.com/readthedocs/sphinx-hoverxref/pull/227

2022-09-25 23:16 UTC, onerandomusername commented on docs/_templates/layout.html
> +  <link rel="stylesheet" href="{{ pathto(css, 1)|e }}?bust=1" type="text/css" />
its been several months, the cache bust is no longer necessary.

2022-10-04 03:39 UTC, onerandomusername commented on docs/_templates/layout.html
> +  <link rel="stylesheet" href="{{ pathto(css, 1)|e }}?bust=1" type="text/css" />
edit: nvm

2022-10-04 03:47 UTC, onerandomusername commented
Due to the cache bust and other general speedups here, I'd *like* to merge this after #722 unless there is an extended period after this pr is ready and #722 is still not ready.

2022-10-04 10:34 UTC, shiftinv commented
> Due to the cache bust

that only affects select files and shouldn't be relevant to #722, I think.
It might be worth consideration to actually do that for all js files, may be difficult to do with sphinx though.

2022-10-16 05:02 UTC, onerandomusername commented
This PR as it is currently breaks the dark theme toggle.

2022-10-16 20:27 UTC, bast0006 commented
It's just the cache bust doing it (sigh). Pushing a fix shortly.

2022-10-24 18:30 UTC, onerandomusername approved these changes
lgtm

2022-10-24 19:15 UTC, shiftinv approved these changes
other than this tiny change, lgtm. Thanks for adding this to hoverxref upstream!

2022-10-24 19:15 UTC, shiftinv commented on docs/_static/custom.js
> +      console.log(rule.constructor.name);
```suggestion
```

2022-10-24 19:22 UTC, merged