bitrate param in create_stage_channel
DisnakeDev/disnake pull request #571
Opened 2022-06-16 18:40 UTC by ResetXD

## Summary

#570 

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [x] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-16 18:41 UTC, ResetXD commented
prob wont hurt much

2022-06-17 20:56 UTC, onerandomusername requested changes
Looks good, just needs the version added indicator

2022-06-17 20:56 UTC, onerandomusername commented on disnake/guild.py
> +            The channel's preferred audio bitrate in bits per second.
```suggestion
        bitrate: :class:`int`
            The channel's preferred audio bitrate in bits per second.
            
            .. versionadded:: 2.6

```

2022-06-17 21:27 UTC, onerandomusername approved these changes

2022-06-17 21:39 UTC, merged