fix: correctly handle unions in `verify_type`
DisnakeDev/disnake pull request #584
Opened 2022-06-26 18:52 UTC by shiftinv

## Summary

Fixes #577.

An annotation like `Union[User, Member]` passes the `issubclass_(self.type, disnake.Member)` check since `issubclass_` explicitly handles unions; the following `isinstance(argument, disnake.Member)` check did not accept `User` objects, even though they should've been permitted based on the annotation type.
This PR improves the validation logic to correctly handle cases like this as well.

Regression from #283 - third test case of `test_verify_type` checks for this particular one.

## Checklist

- [x] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-07-01 07:59 UTC, onerandomusername requested changes

2022-07-01 10:25 UTC, onerandomusername commented on disnake/ext/commands/params.py
> +        """Check if the type of an argument is correct and possibly raise if it's not"""
style: needs a `.`

2022-07-01 18:55 UTC, shiftinv commented on disnake/ext/commands/params.py
> +        """Check if the type of an argument is correct and possibly raise if it's not"""
c00fbe7a0d956c54fa3eb54110bb0c62b9e2f2ca

2022-07-01 18:57 UTC, shiftinv commented on disnake/ext/commands/params.py
> +        if self.discord_type.value not in (6, 9):
Benchmarked a few alternatives, the one in 5cedadf80cfa84c1b4088fc297776cd7400cf535 seems to be the fastest one, even being slightly faster than the old check.

2022-07-02 13:38 UTC, onerandomusername requested changes
This still has a minor bug with users and members:
![image](https://user-images.githubusercontent.com/71233171/177003266-f48c963b-dae6-47ee-b37d-b3aad28b6dc5.png)
```py
    @parent.sub_command("user")
    async def user(self, itr: disnake.CommandInteraction, user: disnake.User):
        await itr.send(type(user))
```

2022-07-02 15:03 UTC, shiftinv commented
> This still has a minor bug with users and members

~~it's not a bug, it's a feature~~
But yeah, that seems to be working as intended, even if `Member` doesn't inherit from `User` it ends up having the same attributes+methods due to `@flatten_user`

2022-07-02 15:04 UTC, onerandomusername commented
Sounds good, then.

2022-07-02 15:04 UTC, onerandomusername approved these changes

2022-07-02 15:07 UTC, merged