typing(ui): add `slice` to `ActionRow.__getitem__` and `__delitem__` annotations
DisnakeDev/disnake pull request #624
Opened 2022-07-14 18:11 UTC by shiftinv

## Summary

Fixes type-checking for expressions like `row[1:4]` and `del row[2:3]`.

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-07-14 21:27 UTC, EQUENOS approved these changes

2022-07-14 21:31 UTC, Chromosomologist commented
Ah, good idea, actually; I forgot about slices when I did the refactor. Anyways, LGTM!

2022-07-16 02:52 UTC, onerandomusername requested changes

2022-07-16 02:52 UTC, onerandomusername commented on disnake/ui/action_row.py
> +            Returns an iterator for the components in this row.
missing versionadded indicators.

2022-07-16 12:01 UTC, shiftinv commented on disnake/ui/action_row.py
> +            Returns an iterator for the components in this row.
https://github.com/DisnakeDev/disnake/pull/624/commits/aba82f40a1b97986b8ba0351abea3d971f165435

2022-07-16 17:34 UTC, onerandomusername approved these changes
looks good, thanks

2022-07-16 17:38 UTC, merged