feat: add application command flag
DisnakeDev/disnake pull request #649
Opened 2022-07-22 06:09 UTC by toolifelesstocode

## Summary

This pull request adds the new `APPLICATION_COMMAND_BADGE` flag that was documented on https://github.com/discord/discord-api-docs/pull/5222.

## Checklist

- [ ] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-07-22 07:25 UTC, onerandomusername requested changes

2022-07-22 07:25 UTC, onerandomusername commented on disnake/flags.py
> +        return 1 << 23
missing a versionadded indicator

2022-07-22 07:25 UTC, onerandomusername commented on changelog/649.feature.rst
> +Add the new ``APPLICATION_COMMAND_BADGE`` flag.
```suggestion
Add :attr:`ApplicationFlags.application_command_badge` flag which shows whether an application has at least one globally registered application command.
```

2022-08-26 23:35 UTC, shiftinv approved these changes
docs PR was merged, lgtm

2022-08-26 23:38 UTC, merged