Turn `Client.i18n` into property
DisnakeDev/disnake pull request #661
Opened 2022-07-27 17:34 UTC by ItsAleph

## Summary

Fixes #652

Due to [sphinx-doc/sphinx#741](https://github.com/sphinx-doc/sphinx/issues/741), Sphinx's autodoc did not documented attributes of inherited classes until Sphinx 3.5. Looks like this issue popped up yet again, thus I turned `disnake.Client.i18n` into property

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [x] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-07-27 22:57 UTC, onerandomusername requested changes
Two comments, other than it looks good.

2022-07-27 22:57 UTC, onerandomusername commented on disnake/ext/commands/bot.py
> +    i18n: :class:`.LocalizationProtocol`
missing a new line to be consistent
```suggestion
        .. versionadded:: 2.5

    i18n: :class:`.LocalizationProtocol`
```

2022-07-27 22:57 UTC, onerandomusername commented on changelog/652.doc.rst
> +:class:`.ext.commands.Bot` and :class:`.ext.commands.InteractionBot` class references now document :class:`Client.i18n` attribute
Needs a period at the end.
```suggestion
|commands| Document the ``i18n`` attribute on :class:`.ext.commands.Bot` and :class:`.ext.commands.InteractionBot` classes.
```

2022-07-28 00:22 UTC, onerandomusername approved these changes
lgtm

2022-07-28 00:22 UTC, shiftinv approved these changes

2022-07-28 00:23 UTC, merged