feat: support regex automod
DisnakeDev/disnake pull request #794
Opened 2022-10-07 02:47 UTC by onerandomusername

## Summary

implements https://github.com/discord/discord-api-docs/pull/5504/files

Because that isn't released, this isn't tested yet.
## Checklist

- [ ] If code changes were made, then they have been tested
    - [x] I have updated the documentation to reflect the changes
    - [x] I have formatted the code properly by running `task lint`
    - [x] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [x] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-10-07 13:05 UTC, shiftinv requested changes

2022-10-07 13:05 UTC, shiftinv commented on disnake/automod.py
> +        ...
```suggestion
    def __init__(self, *, keyword_filter: Sequence[str], regex_patterns: Sequence[str] = ...):
        ...

    @overload
    def __init__(self, *, keyword_filter: Sequence[str] = ..., regex_patterns: Sequence[str]):
        ...
```

2022-10-07 13:05 UTC, shiftinv commented on changelog/794.feature.rst
> +Support regex within automod. Adds :attr:`AutoModTriggerMetadata.regex_patterns`
```suggestion
Support regex within automod using :attr:`AutoModTriggerMetadata.regex_patterns`.
```

2022-10-08 14:19 UTC, shiftinv commented
The documentation for `AutoModActionExecution.matched_keyword` should mention regular expressions as well, looks like that field is being reused:
```json
{
    "t": "AUTO_MODERATION_ACTION_EXECUTION",
    "s": 12,
    "op": 0,
    "d": {
        "user_id": "",
        "rule_trigger_type": 1,
        "rule_id": "984891789930557500",
        "matched_keyword": "literally 1\\s*9\\s*8\\s*4",
        "matched_content": "literally 1 9 8 4",
        "content": "wow this is literally 1 9 8 4 smh",
        ...
    }
}
```

2022-10-17 03:58 UTC, onerandomusername commented
@shiftinv I added a mention of matched_keyword possibly containing regex in https://github.com/DisnakeDev/disnake/pull/794/commits/5805f24e91be22daa4d22174feb18348a9bff3e6

2022-10-23 21:26 UTC, shiftinv commented on disnake/automod.py
> +            If this rule matched because of a regex, this will contain the matching regex.
```suggestion
        The keyword or regex that matched.
```

2022-11-03 19:59 UTC, shiftinv approved these changes

2022-11-04 20:50 UTC, shiftinv commented on disnake/automod.py
> +        A maximum of 10 regexes can be added.
```suggestion
        A maximum of 10 regexes can be added, each with up to 75 characters.
```

2022-11-04 20:50 UTC, shiftinv commented on disnake/automod.py
>          for details about how keyword matching works.
```suggestion
        for details about how keyword matching works.
        Each keyword must be 30 characters or less.
```

2022-11-04 22:04 UTC, merged